version: '2.3'
services:
  zookeeper:
    container_name: zookeeper
    hostname: zookeeper.pendev
    build: ./docker/zookeeper
    command: /opt/zookeeper/bin/zkServer.sh start-foreground
    healthcheck:
      test: ["CMD-SHELL", "jps | grep --silent QuorumPeer"]
      interval: 30s
      timeout: 10s
      retries: 3
    ports:
      - "2181:2181"
    networks:
      default:
        aliases:
          - zookeeper.sitewatcher
  kafka:
      container_name: kafka
      build: ./docker/kafka
      command: /opt/kafka/bin/kafka-server-start.sh /opt/kafka/config/server.properties
      volumes:
        - kafka_data:/data/kafka
      depends_on:
        zookeeper:
          condition: service_healthy
      ports:
        - "9092:9092"
      networks:
        default:
          aliases:
            - kafka.sitewatcher

  postgres:
    container_name: postgres
    image: postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: sitewatcher
      POSTGRES_PASSWORD: sitewatcher
      POSTGRES_DATABASE: sitewatcher
    networks:
      default:
        aliases:
          - postgres.sitewatcher
    volumes:
      - sitewatchdata:/var/lib/postgresql/data
volumes:
  sitewatchdata:
  kafka_data: